### ISSUE TITLE
`prelink` missing as a dependency for x11-drivers/nvidia-drivers-384.69 (and others)

### ISSUE THREAD

**Issue by bluecube** [sjnewbury/gentoo-gpu#13]
When compiling x11-drivers/nvidia-drivers-384.69 I get a build failure saying: 

    `/tmp/portage/x11-drivers/nvidia-drivers-384.69/temp/environment: line 5092: prelink: command not found`

Quick grep through the ebuilds shows that the `prelink` command is used in all of them, but only 304.135-r1 and 340.102-r1 specify it as a dependency. 

Emerging prelink manually in advance fixes this.

Relevant bit from the build log:

    >>> Install nvidia-drivers-384.69 into /tmp/portage/x11-drivers/nvidia-drivers-384.69/image/ category x11-drivers
     * Installing nvidia module
     * Installing nvidia-uvm module
     * Installing nvidia-modeset module
     * Installing nvidia-drm module
    make -j8 -C /tmp/portage/x11-drivers/nvidia-drivers-384.69/work//nvidia-settings-384.69/src/ DESTDIR=/tmp/portage/x11-drivers/nvidia-drivers-384.69/image/ GTK3_AVAILABLE=1 LIBDIR=/tmp/portage/x11-drivers/nvidia-drivers-384.69/image//usr/lib64 NV_USE_BUNDLED_LIBJANSSON=0 NV_VERBOSE=1 PREFIX=/usr DO_STRIP= install 
    make: Entering directory '/tmp/portage/x11-drivers/nvidia-drivers-384.69/work/nvidia-settings-384.69/src'
    make[1]: Entering directory '/tmp/portage/x11-drivers/nvidia-drivers-384.69/work/nvidia-settings-384.69/src/libXNVCtrl'
    make[1]: Nothing to be done for 'default'.
    make[1]: Leaving directory '/tmp/portage/x11-drivers/nvidia-drivers-384.69/work/nvidia-settings-384.69/src/libXNVCtrl'
    mkdir -p /tmp/portage/x11-drivers/nvidia-drivers-384.69/image//usr/lib64
    install -m 644 _out/Linux_x86_64/libnvidia-gtk2.so \
        /tmp/portage/x11-drivers/nvidia-drivers-384.69/image//usr/lib64/libnvidia-gtk2.so.384.69
    install -m 644 _out/Linux_x86_64/libnvidia-gtk3.so \
        /tmp/portage/x11-drivers/nvidia-drivers-384.69/image//usr/lib64/libnvidia-gtk3.so.384.69
    mkdir -p /tmp/portage/x11-drivers/nvidia-drivers-384.69/image//usr/bin
    install -m 755 _out/Linux_x86_64/nvidia-settings /tmp/portage/x11-drivers/nvidia-drivers-384.69/image//usr/bin/nvidia-settings
    make: Leaving directory '/tmp/portage/x11-drivers/nvidia-drivers-384.69/work/nvidia-settings-384.69/src'
    /tmp/portage/x11-drivers/nvidia-drivers-384.69/temp/environment: line 5092: prelink: command not found
     * ERROR: x11-drivers/nvidia-drivers-384.69::gentoo-gpu failed (install phase):
     *   /tmp/portage/x11-drivers/nvidia-drivers-384.69/image/usr/lib64/libnvidia-gtk3.so.384.69: relocation failed!
     * 
     * Call stack:
     *     ebuild.sh, line  115:  Called src_install
     *   environment, line 5044:  Called src_install-libs
     *   environment, line 5092:  Called die
     * The specific snippet of code:
     *           prelink --reloc-only=$(printf "%05d" ${addr}) ${shared_lib} || die "${shared_lib}: relocation failed!";
     * 
     * If you need support, post the output of `emerge --info '=x11-drivers/nvidia-drivers-384.69::gentoo-gpu'`,
     * the complete build log and the output of `emerge -pqv '=x11-drivers/nvidia-drivers-384.69::gentoo-gpu'`.
     * The complete build log is located at '/tmp/portage/x11-drivers/nvidia-drivers-384.69/temp/build.log'.
     * The ebuild environment file is located at '/tmp/portage/x11-drivers/nvidia-drivers-384.69/temp/environment'.
     * Working directory: '/tmp/portage/x11-drivers/nvidia-drivers-384.69/work'
     * S: '/tmp/portage/x11-drivers/nvidia-drivers-384.69/work/'
     * QA Notice: command not found:
     * 
     * 	/tmp/portage/x11-drivers/nvidia-drivers-384.69/temp/environment: line 5092: prelink: command not found

**Comment by sjnewbury** [comment]
Good catch will fix this up.

**Comment by sjnewbury** [comment]
done
