### ISSUE TITLE
dev-util/clinfo is in Portage; please remove from this overlay

### ISSUE THREAD

**Issue by candrews** [sjnewbury/gentoo-gpu#15]
dev-util/clinfo is in Portage:
https://github.com/gentoo/gentoo/tree/master/dev-util/clinfo

Therefore, can you please remove it from this overlay?

**Comment by sjnewbury** [comment]
Yes, of course.  Will get right on it!  Sorry for taking so long since my last update... :-)

**Comment by sjnewbury** [comment]
done
