### ISSUE TITLE
A file listed in the Manifest could not be found: libclc-0.2.0_p20160921-r1.ebuild

### ISSUE THREAD

**Issue by bluecube** [sjnewbury/gentoo-gpu#21]
After fresh `layman -a gentoo-gpu` I got the following error:

```A file listed in the Manifest could not be found: /var/lib/layman/gentoo-gpu/dev-libs/libclc/libclc-0.2.0_p20160921-r1.ebuild```

Running `ebuild <that_file> digest` fixes it.

**Comment by sjnewbury** [comment]
Sorry for taking almost a year to get back to this.  The overlay will be updated shortly.
